import error
PS D:\python\bro code> python -u "d:\python\bro code\random.py"
Traceback (most recent call last):
  File "d:\python\bro code\random.py", line 3, in <module>
    from random import randint
  File "d:\python\bro code\random.py", line 3, in <module>
    from random import randint
ImportError: cannot import name 'randint' from partially initialized module 'random' (most likely due to a circular import) (d:\python\bro code\random.py)
PS D:\python\bro code>